# Generated by Django 4.2.20 on 2025-03-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movecounter',
            old_name='jump_count',
            new_name='DLJ_counter',
        ),
        migrations.RenameField(
            model_name='movecounter',
            old_name='releve_count',
            new_name='DLR_counter',
        ),
        migrations.AddField(
            model_name='movecounter',
            name='SLJ_L_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movecounter',
            name='SLJ_R_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movecounter',
            name='SLR_L_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movecounter',
            name='SLR_R_counter',
            field=models.IntegerField(default=0),
        ),
    ]
